<div class="container">
    <div class="bagckround-competence"></div>
    <div class="competence-projet">
        <div class="title">
            <h1>Integration</h1>
            <p>Site responsive</p>
        </div>

        <div class="competence-projet-column">
            <div class="competence-projet-image">
                <img src="https://www.olivier-guilleux.com/wp-content/uploads/2017/10/zebra-partners-website-homepage.jpg" alt="">
            </div>
        </div>

        <div class="competence-projet-column">
            <div class="competence-projet-description">
                <ul>
                    <li>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo expedita odio esse perferendis accusantium repellendus magni quos quod rem quasi animi maxime accusamus dicta, cum ipsam, sequi quis corrupti iusto.</p>
                    </li>
                    <li><span>Compétences :</span>
                        <i tooltip="HTML5" class="devicon-html5-plain devicon "></i>
                        <i tooltip="CSS3" class="devicon-css3-plain devicon"></i>
                        <i tooltip="JavaScript" class="devicon-javascript-plain devicon"></i>
                        <i tooltip="Jquery" class="devicon-jquery-plain devicon"></i>
                    </li>
                    <li><span>Outil : </span>
                        <i tooltip="GitHub" class="devicon-github-plain devicon"></i>
                        <i tooltip="Git" class="devicon-git-plain devicon"></i>
                        <i tooltip="Bootsrap" class="devicon-bootstrap-plain devicon"></i>
                        <i tooltip="Bower" class="devicon-bower-plain devicon"></i>
                        <i tooltip="Atom" class="devicon-atom-original devicon"></i> 
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>