<div class="container">
    <div class="competence-projet">
        <div class="title">
            <h1>Integration</h1>
            <p>Site responsive</p>
        </div>

        <div class="competence-projet-column">
            <div class="competence-projet-image">
                <img src="https://www.olivier-guilleux.com/wp-content/uploads/2017/10/zebra-partners-website-homepage.jpg" alt="">
            </div>
        </div>

        <div class="competence-projet-column">
            <div class="competence-projet-description">
                <ul>
                    <li>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo expedita odio esse perferendis accusantium repellendus magni quos quod rem quasi animi maxime accusamus dicta, cum ipsam, sequi quis corrupti iusto.</p>
                    </li>
                    <li><span>Compétences :</span>
                        <i class="devicon-html5-plain"></i> <i class="devicon-css3-plain"></i> <i class="devicon-javascript-plain"></i> <i class="devicon-jquery-plain"></i>
                    </li>
                    <li><span>Outil : </span>
                        <i class="devicon-github-plain"></i> <i class="devicon-git-plain"></i>  <i class="devicon-bootstrap-plain"></i> <i class="devicon-bower-plain"></i> <i class="devicon-atom-original"></i> BRACKET, SUBLIME TEXT
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>