<div class="container">
    <div class="contact-container">
        <div class="background-contact"></div>
        <div class="home-contact-title">
            <h2>Contact</h2>
        </div>
        <div class="contact-form">
            <form method="POST" class="contact">
                <div class="input-block">
                    <label>Nom</label>
                    <input type="text" name="" class="form-control form">
                </div>
                <div class="input-block">
                    <label>Email</label>
                    <input type="text" name="" class="form-control form">
                </div>
                <div class="input-block">
                    <label>Message</label>
                    <textarea name="" id="" class="form-control form" cols="30" rows="10"></textarea>
                </div>
                <div class="">
                    <button id="singlebutton" value="editPassword" type="submit" name="action" class="btn-msg btn-animate"><span>Envoyer</span></button>
                </div>

            </form>
        </div>

    </div>
</div>