<div class="footer">
    <div class="container">
        <div class="footer-line">
            <div class="footer-column">
                <span> © Copyright 2018 </span>
                <ul>
                    <li>Tous drois résevé</li>
                </ul>
            </div>

            <div class="footer-column">
                <ul>
                    <a href="" class="icone-fab">
                        <li><i tooltip="Linkedin" class="fab fa-linkedin"></i></li>
                    </a>
                    <a href="https://github.com/ighmouraceneb">
                        <li><i tooltip="Github" class="fab fa-github-square"></i>

                        </li>
                    </a>
                    <a href="https://codepen.io/bilaDev/">
                        <li><i tooltip="Codepen" class="fab fa-codepen"></i>

                        </li>
                    </a>
                </ul>
            </div>
        </div>
    </div>
</div>