<section class="home-head-skill">
    <section class="home-head">
        <?php require('apps/slider.php');?>
    </section>

    <section class="home-skill">
        <?php require('apps/skill.php');?>
    </section>

    <section class="home-portfolio">
        <?php require('apps/portfolio.php');?>
    </section>

    <section class="home-contact">
        <?php require('apps/contact.php');?>
    </section>
</section>