<input id="nav-mobile" type="checkbox">
<nav class="nav-mobile">
    <label class="nav-open" for="nav-mobile"></label>
    <div>
        <label class="nav-close" for="nav-mobile"></label>
        <a href="#">Profil</a>
        <a href="#">Compétences</a>
        <a href="#">Projets</a>
        <a href="#">Contact</a>
        
    </div>
</nav>
<nav class="nav-general">
    <div class="nav-list">
        <a href="#profil">Profil</a>
        <a href="#competences">Compétences</a>
        <a href="#projets">Projets</a>
        <a href="#contact">Contact</a>

    </div>
</nav>
    
