<div class="home-portfolio-content">
    <div class="home-portfolio-title">
        <h2>Ma devise  Créativité, Sécurité et confiance</h2>
    </div>

    <div class="home-portfolio-column">
        <div class="projet-description">
            <img src="https://cdn-images-1.medium.com/max/2000/1*RNrSl5f--NSiBI-5yeCHJA.jpeg" alt="">
        </div>
        <div class="projet-info">
            <div class="year">Année : 2017</div>
            <div class="title">Projet : IESH ALSACE</div>
        </div>
    </div>
    
    <div class="home-portfolio-column">
        <div class="projet-description">
            <img src="https://helpx.adobe.com/fr/creative-cloud/how-to/create-portfolio-website/_jcr_content/main-pars/image_620560438.img.jpg/create-portfolio-website_1800x1012.jpg" alt="">
        </div>

        <div class="projet-info">
            <div class="year">Année : 2018</div>
            <div class="title">Projet : Portfolio</div>
        </div>
    </div>



</div>