<div class="container">
    <div class="portfolio-projet">
        <div class="title">
            <h1>IESH d'Alsace</h1>
            <p>Institut de formation</p>
        </div>

        <div class="portfolio-projet-column">
            <div class="portfolio-projet-image">
                <img src="https://www.olivier-guilleux.com/wp-content/uploads/2017/10/zebra-partners-website-homepage.jpg" alt="">
            </div>
        </div>

        <div class="portfolio-projet-column">
            <div class="portfolio-projet-description">
                <ul>
                    <li>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo expedita odio esse perferendis accusantium repellendus magni quos quod rem quasi animi maxime accusamus dicta, cum ipsam, sequi quis corrupti iusto.</p>
                    </li>
                    <li><span>Année :</span>2017</li>
                    <li><span>Client : </span>IESH</li>
                    <li><span>Mission : </span>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </li>
                    <li>
                        <a href="" class="btn-skill "><span>Vister le site</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>