<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Starter Template for Bootstrap</title>
    <link href="public/styles/reset.css" rel="stylesheet">
    <!-- font  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!-- menu CSS -->
    <link href="public/styles/nav.css" rel="stylesheet">
    <!-- home CSS -->
    <link href="public/styles/home.css" rel="stylesheet">
    <link href="public/styles/style.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <style type="text/css">

        .starter-template {
            padding: 3rem 1.5rem;
            text-align: center;
        }
    </style>
</head>


<body>
    <!-- .navBarre -->
    <header>
        <?php require( 'apps/header.php');?>
    </header>

    <!-- /.navBarre -->

    <!-- .container -->
    <div class="page-content">
        <?php require( 'apps/content.php');?>

    </div>
    <!-- /.container -->
    <!-- .footer -->
    <?php require( 'apps/footer.php');?>
    <!-- /.footer -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>


</body>

</html>