<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Starter Template for Bootstrap</title>
    <link href="public/styles/reset.css" rel="stylesheet">
    <!-- font  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="public/styles/font-awesome.min.css" rel="stylesheet">
    <!-- icone programmation -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <!-- menu CSS -->
    <link href="public/styles/nav.css" rel="stylesheet">
    <!-- home CSS -->
    <link href="public/styles/home.css" rel="stylesheet">
    <link href="public/styles/style.css" rel="stylesheet">
    <!-- Custom styles for this template -->

</head>


<body>
    <!-- .navBarre -->
    <header>
        <?php require( 'apps/header.php');?>
    </header>

    <!-- /.navBarre -->

    <!-- .container -->
    <div class="page-content">
        <?php require( 'apps/content.php');?>
    </div>
    <!-- /.container -->
    <!-- .footer -->
    <?php require( 'apps/footer.php');?>
    <!-- /.footer -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<script src="public/scripts/script.js"></script>


</body>

</html>