<div class="home-skill-content">
    <div class="home-skill-title">
        <h2>Compétences</h2>
    </div>
    <div class="home-skill-ligne-image">
        <img src="public/images/ligne-point.png" alt="">
    </div>
    <div class="skills">
        <div class="home-skill-column">
            <h3>Développement</h3>
            <i class="devicon-html5-plain colored"></i>
            <i class="devicon-css3-plain colored"></i>
            <i class="devicon-javascript-plain colored"></i>
            <i class="devicon-bootsrap-plain colored"></i>
            <i class="devicon-php-plain"></i>
            <i class="devicon-laravel-plain"></i>
        </div>
        <div class="home-skill-column">
            <h3>Développement</h3>
            <i tooltip="Html5" class="devicon-html5-plain colored"></i>
            <i class="devicon-php-plain"></i>
        </div>
        <div class="home-skill-column">
            <h3>Développement</h3>
            <i tooltip="Html5" class="devicon-html5-plain colored"></i>
            <i class="devicon-php-plain"></i>
        </div>
    </div>
</div>