<div class="home-skill-content">
    <div class="home-skill-title">
        <h2>Compétences</h2>
    </div>

    <div class="home-skill-column skills">
        <h3>
                Je réalise des sites internet avec le souci du détail et un rendu fidèle au design.
        </h3>
        <ul id="accordion">
            <li>
                <div class="skill-title integration">
                    <h2><span>01. </span>Intégration</h2>
                </div>
                <div class="presentation-integration" style="display:none">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam magni facere minus optio reiciendis? Sed iusto ipsum praesentium eum voluptatibus alias libero, sit amet doloremque, exercitationem veniam, debitis distinctio illo.</p>
                    <a href="" class="btn-skill"><span>Explorer</span></a>
                </div>
            </li>
            <li>
                <div class="skill-title developpement">
                    <h2><span>02. </span>Développement</h2>
                </div>
                <div class="presentation-developpement" style="display: none">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta reiciendis incidunt laboriosam esse repellat, enim cum doloremque odit omnis labore mollitia eaque, perferendis facilis. Mollitia, earum, nobis! Soluta quae, pariatur!</p>
                    <a href="" class="btn-skill"><span>Explorer</span></a>
                </div>
            </li>
            <li>
                <div class="skill-title outil">
                    <h2><span>03. </span>Outil</h2>
                </div>
                <div class="presentation-outils " style="display: none">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum omnis maxime, nam voluptates delectus ratione velit blanditiis, pariatur deserunt nobis ut amet saepe labore veritatis fugiat aliquam. Consectetur, corrupti, sit?</p>
                    <a href="" class="btn-skill"><span>Explorer</span></a>
                </div>
            </li>
        </ul>
    </div>
    
    <div class="home-skill-column">
        <div class="home-skill-image"></div>
    </div>
</div>