<div class="home-head-column">
    <a href="">
        <div class="home-head-image image-web">
            <div class="home-head-content">
                <h1 class="home-head-title">Création de sites et d'applications webs</h1>
                <p class="home-head-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

            </div>
        </div>
    </a>
</div>
<div class="home-head-column">
    <a href="">
        <div class="home-head-image image-formation">
            <div class="home-head-content">
                <h1 class="home-head-title">Formations</h1>
                <p class="home-head-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>

            </div>
        </div>
    </a>

    <a href="">
        <div class="home-head-image souscription">
            <div class="home-head-content">
                <h1 class="home-head-title">Blog</h1>
                <p class="home-head-description">Découvrez nous différents tutos gratuits.</p>
                <button>Abonnez-vous à notre newsletter</button>

            </div>
        </div>
    </a>
</div>
